/*
 * Copyright 2023 Omico
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
@file:JvmName("DslGenerator")

package me.omico.elucidator

import com.squareup.kotlinpoet.FileSpec
import me.omico.elucidator.function.addDslScopeExtensionFunctions
import me.omico.elucidator.function.addInteroperabilityFunction
import me.omico.elucidator.type.addDslBuilderClass
import me.omico.elucidator.type.addDslScopeInterface
import kotlin.io.path.Path

fun main(arguments: Array<String>) {
    val outputDirectory = Path(arguments.first())
    generatedTypes.forEach { type ->
        FileSpec.builder(GENERATED_PACKAGE_NAME, type.generatedFileName)
            .addFileComment(GENERATED_HEADER_COMMENT)
            .addDslScopeInterface(type)
            .addDslBuilderClass(type)
            .addInteroperabilityFunction(type)
            .addDslScopeExtensionFunctions(type)
            .build()
            .writeTo(outputDirectory)
    }
}

internal const val GENERATED_PACKAGE_NAME = "me.omico.elucidator"

private val GENERATED_HEADER_COMMENT: String =
    """
    |
    |Generated by DslGenerator from Elucidator. Do not edit directly!!!
    |
    """.trimMargin()
