package me.omico.gradm.internal.codegen

import me.omico.gradm.internal.path.GradmPaths
import java.nio.file.Files

internal fun generateGradleBuildScript(gradmVersion: String) {
    Files.write(
        GradmPaths.GeneratedDependenciesProject.gradleBuildScript,
        gradleBuildScriptContent(gradmVersion).toByteArray(),
    )
}

private fun gradleBuildScriptContent(gradmVersion: String): String =
    """
    //
    // Generated by Gradm, will be overwritten by every dependencies update, do not edit!!!
    //

    plugins {
        `embedded-kotlin`
    }

    kotlin {
        target.compilations.all {
            kotlinOptions {
                jvmTarget = "11"
            }
        }
    }

    repositories {
        mavenCentral()
        mavenLocal()
    }

    dependencies {
        compileOnly(gradleApi())
        compileOnly(gradleKotlinDsl())
        compileOnly(embeddedKotlin("gradle-plugin-api"))
        implementation("me.omico.gradm:gradm-runtime:$gradmVersion")
    }

    """.trimIndent()
