name: Deploy snapshot

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-snapshot.yml'
      - 'gradm-*'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
  workflow_dispatch:

jobs:
  build:
    if: "!startswith(github.event.head_commit.message, 'release: ')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
        env:
          IS_GITHUB_ACTIONS: true
          NEXUS_PUBLISH_SNAPSHOT_URL: ${{ secrets.NEXUS_PUBLISH_SNAPSHOT_URL }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        with:
          arguments: spotlessCheck clean publish
